services:
  - type: web
    name: mern-backend
    env: node
    rootDir: server
    buildCommand: "npm install"
    startCommand: "node server.js"
    plan: free
    autoDeploy: true
    envVars:
      - key: MONGO_URI
        sync: false
      - key: CLIENT_SECRET_KEY
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
